### ISSUE TITLE
"Ähnliche Ressourcen" needs English version for English posts

### ISSUE THREAD

**Issue by ekoenigshofer** [acdh-oeaw/howto#177]
The "Ähnliche Resssourcen" at the end of posts remains the same, no matter if the post above is German or English.For English pages, it would make sense to have "Siminar ressources" instead.
also, is it possible - e.g. like when I would like to show all posts in a curricula to prioritize a tag and have only ressources show that have that tag (e.g. now if I have posts outside a curriculum that relate to the same tag, they are also included). Or alternative a "previous: Lesson X" and "next: Lesson Y" option to navigate through the curriculum in the intended order (or would we not want an intended order to show although we create it in the curriculum setup?)

The above has been noticed as a usability opportunity/ issue when working on the SemanticKraus posts, if this is relevant.

**Comment by ekoenigshofer** [comment]
edit: Semantic Kraus is not yet online as a curriculum because I wanted the first 2 posts to be ready- so it makes sense to have a curriculum

**Comment by stefanprobst** [comment]
- i think it makes sense to keep the "similar resources" as is, namely randomly picking other resources which share at least one keyword.
- i also agree that it would be good to have some navigation controls for articles which are part of a curriculum. - problem is that currently an article can be part of multiple curricula, so it's not clear *which* navigation to show
- currently, we only indicate in the left sidebar which curricula an article is included in ("Contained in")
- our current i18n strategy is that there is a language toggle in the page header, which only affects UI, but does not care about content language. this was an intentional choice (not by me) but i'm very open to revisit this. i think toggling the language should also toggle which articles are shown.
